description: Welcome to CompSoc Edinburgh. We are the Computer Science and AI society.

sass:
   sourcemap: true

url: "http://comp-soc.com"
baseurl: "/compsoc-website" # does not include hostname

collections:
  minutes:
    output: true
    permalink: "/:collection/:path"
  pages:
    output: true
    permalink: /:path
  posts:
    output: true
    permalink: "/blog/:categories/:year/:month/:day/:title.html"
    
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

  - scope:
      path: ""
      type: minutes
    values:
      layout: minutes # minute page

  - scope:
      path: ""
      type: pages
    values:
      layout: page

  - scope:
      path: ""
      type: posts
    values:
      layout: post
