description: Welcome to CompSoc Edinburgh. We are the Computer Science and AI society.

sass:
   sourcemap: true

url: "http://comp-soc.com"
baseurl: "" # does not include hostname

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
